# Generated by Django 4.2.4 on 2023-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='long_url',
            field=models.CharField(max_length=1000),
        ),
    ]
